language: php

php:
 - 7.3

before_script:
 - mkdir plugins
 - wget -O plugins/DevTools.phar https://github.com/IceCruelStuff/DevTools/releases/latest/download/DevTools.phar
 - phpenv config-rm xdebug.ini
 - echo | pecl install channel://pecl.php.net/yaml-2.1.0
 - git clone https://github.com/pmmp/pthreads.git
 - cd pthreads
 - git checkout 646dac62ae0d48c1ada7b007e15575fb84f7d71d
 - phpize
 - ./configure
 - make
 - make install
 - cd ..
 - echo "extension=pthreads.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
 - php tests/TravisTest.php

cache:
 directories:
  - $HOME/.composer/cache/files
  - $HOME/.composer/cache/vcs

notifications:
 email: false
